# Generated by Django 5.2.12 on 2026-05-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('other', 'Other')], default='home', max_length=20),
        ),
        migrations.AddField(
            model_name='address',
            name='country_code',
            field=models.CharField(default='IN', help_text='ISO country code (IN, US, GB, etc.)', max_length=5),
        ),
    ]
