"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
"""
Shopverse Django Settings (Full Utilization Patch Version)
- NO core changes
- Adds full Redis usage + session optimization
- Keeps all existing architecture intact
"""
import os 
from pathlib import Path

from dotenv import load_dotenv
from decouple import config, Csv
import cloudinary
import urllib.parse

# ─────────────────────────────────────────────
# BASE
# ─────────────────────────────────────────────

BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


# ─────────────────────────────────────────────
# CORE SECURITY
# ─────────────────────────────────────────────

SECRET_KEY = config(
    "SECRET_KEY",
    default=os.getenv("DJANGO_SECRET_KEY", "django-insecure-dev-secret-key")
)

DEBUG = config(
    "DEBUG",
    default=False,
    cast=bool
)

ALLOWED_HOSTS = config(
    "ALLOWED_HOSTS",
    default=os.getenv(
        "DJANGO_ALLOWED_HOSTS",
        "127.0.0.1,localhost"
    ),
    cast=Csv()
)

CSRF_TRUSTED_ORIGINS = config(
    "CSRF_TRUSTED_ORIGINS",
    default=os.getenv(
        "CSRF_TRUSTED_ORIGINS",
        "http://127.0.0.1:8000,http://localhost:8000,http://127.0.0.1:5173,http://localhost:5173"
    ),
    cast=Csv()
)


# ─────────────────────────────────────────────
# APPLICATIONS
# ─────────────────────────────────────────────

INSTALLED_APPS = [

    # Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",

    # Third-party
    "django_vite",
    "django_celery_results",
    "cloudinary",
    "cloudinary_storage",

    # Local apps
    "apps.core",
    "apps.accounts",
    "apps.products",
    "apps.cart",
    "apps.orders",
    "apps.payments",
    "apps.delivery",
    "apps.reviews",
    "apps.coupons",
    "apps.wishlist",
    "apps.analytics",
]

# ─────────────────────────────────────────────
# DJANGO VITE
# ─────────────────────────────────────────────

DJANGO_VITE = {
    "default": {
        "dev_mode": DEBUG,
        "dev_server_protocol": "http",
        "dev_server_host": "127.0.0.1",
        "dev_server_port": 5173,

        "static_url_prefix": "dist",

        "manifest_path": BASE_DIR / "static" / "dist" / ".vite" / "manifest.json",
    }
}
# ─────────────────────────────────────────────
# MIDDLEWARE
# ─────────────────────────────────────────────

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",

    # Whitenoise must be immediately after SecurityMiddleware
    "whitenoise.middleware.WhiteNoiseMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "config.urls"

WSGI_APPLICATION = "config.wsgi.application"


# ─────────────────────────────────────────────
# TEMPLATES
# ─────────────────────────────────────────────

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",

        "DIRS": [
            BASE_DIR / "templates"
        ],

        "APP_DIRS": True,

        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "apps.cart.context_processors.cart_item_count",
                "apps.wishlist.context_processors.wishlist_count",
                "apps.core.context_processors.global_data",
            ],
        },
    },
]


# ─────────────────────────────────────────────
# DATABASE
# ─────────────────────────────────────────────
DATABASE_URL = os.getenv("DATABASE_URL")

if DATABASE_URL:
    url = urllib.parse.urlparse(DATABASE_URL)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": url.path[1:],
            "USER": url.username,
            "PASSWORD": url.password,
            "HOST": url.hostname,
            "PORT": url.port or 5432,
            "OPTIONS": {
                "sslmode": "require",
            },
        }
    }
else:
    # Local dev fallback — SQLite
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
# ─────────────────────────────────────────────
# CACHE + SESSIONS
# ─────────────────────────────────────────────
# DEV  → LocMem (no Redis needed)
# PROD → Redis (Railway Redis plugin sets REDIS_URL)
# ─────────────────────────────────────────────

_redis_url = os.getenv("REDIS_URL") or os.getenv("REDIS_CACHE_URL")

if DEBUG:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "shopverse-local-cache",
        }
    }
    SESSION_ENGINE = "django.contrib.sessions.backends.db"

elif _redis_url:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": _redis_url,
        }
    }
    SESSION_ENGINE = "django.contrib.sessions.backends.cache"
    SESSION_CACHE_ALIAS = "default"

else:
    # Safe fallback (no DB tables required)
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "shopverse-prod-cache",
        }
    }
    SESSION_ENGINE = "django.contrib.sessions.backends.db"

SESSION_COOKIE_AGE = 60 * 60 * 24 * 30
SESSION_SAVE_EVERY_REQUEST = True


# ─────────────────────────────────────────────
# AUTHENTICATION
# ─────────────────────────────────────────────

AUTH_USER_MODEL = "accounts.CustomUser"

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"


AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {"min_length": 8},
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# ─────────────────────────────────────────────
# INTERNATIONALIZATION
# ─────────────────────────────────────────────

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True


# ─────────────────────────────────────────────
# STATIC FILES
# ─────────────────────────────────────────────

STATIC_URL = "/static/"

# Only include static/dist if it exists (Vite build output).
# On a clean clone before npm run build this folder won't exist
# and collectstatic would error without this guard.
_static_dir = BASE_DIR / "static"
STATICFILES_DIRS = [_static_dir] if _static_dir.exists() else []

STATIC_ROOT = BASE_DIR / "staticfiles"
# ─────────────────────────────────────────────
# STORAGE
# ─────────────────────────────────────────────

STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


# ─────────────────────────────────────────────
# INTERNAL IPS
# ─────────────────────────────────────────────

INTERNAL_IPS = [
    "127.0.0.1",
    "localhost",
]


# ─────────────────────────────────────────────
# MEDIA FILES (Cloudinary)
# ─────────────────────────────────────────────

MEDIA_URL = "/media/"

CLOUDINARY_STORAGE = {
    "CLOUD_NAME": os.getenv("CLOUDINARY_CLOUD_NAME"),
    "API_KEY": os.getenv("CLOUDINARY_API_KEY"),
    "API_SECRET": os.getenv("CLOUDINARY_API_SECRET"),
    "SECURE": True,
}

cloudinary.config(
    cloud_name=os.getenv("CLOUDINARY_CLOUD_NAME"),
    api_key=os.getenv("CLOUDINARY_API_KEY"),
    api_secret=os.getenv("CLOUDINARY_API_SECRET"),
    secure=True
)


# ─────────────────────────────────────────────
# SECURITY SETTINGS
# ─────────────────────────────────────────────

SESSION_COOKIE_HTTPONLY = True

SECURE_REFERRER_POLICY = "same-origin"

SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"

# Railway terminates TLS at its proxy and forwards HTTP internally.
# SECURE_SSL_REDIRECT must be False — Railway's proxy handles HTTPS.
# The SECURE_PROXY_SSL_HEADER below tells Django the connection is
# already secure when Railway sets X-Forwarded-Proto: https.
SECURE_SSL_REDIRECT = False

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

SESSION_COOKIE_SECURE = False if DEBUG else True

CSRF_COOKIE_SECURE = False if DEBUG else True

SECURE_BROWSER_XSS_FILTER = True

SECURE_CONTENT_TYPE_NOSNIFF = True

X_FRAME_OPTIONS = "DENY"

SECURE_HSTS_SECONDS = 0 if DEBUG else 31536000

SECURE_HSTS_INCLUDE_SUBDOMAINS = False if DEBUG else True

SECURE_HSTS_PRELOAD = False if DEBUG else True


# ─────────────────────────────────────────────
# DEFAULT PRIMARY KEY
# ─────────────────────────────────────────────

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ─────────────────────────────────────────────
# STRIPE CONFIG
# ─────────────────────────────────────────────

STRIPE_PUBLIC_KEY = os.getenv("STRIPE_PUBLIC_KEY")

STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY")

STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET")

STRIPE_CURRENCY = "inr"


# ─────────────────────────────────────────────
# EMAIL CONFIGURATION
# ─────────────────────────────────────────────

EMAIL_BACKEND = config(
    "EMAIL_BACKEND",
    default="django.core.mail.backends.console.EmailBackend"
)

EMAIL_HOST = config("EMAIL_HOST", default="")

EMAIL_PORT = config("EMAIL_PORT", default=587, cast=int)

EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")

EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")

EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True, cast=bool)

DEFAULT_FROM_EMAIL = config(
    "DEFAULT_FROM_EMAIL",
    default="noreply@shopverse.com"
)


# ─────────────────────────────────────────────
# CELERY CONFIG
# ─────────────────────────────────────────────

_celery_broker = os.getenv("CELERY_BROKER_URL") or os.getenv("REDIS_URL")
_celery_backend = os.getenv("CELERY_RESULT_BACKEND") or os.getenv("REDIS_URL")

if DEBUG or not _celery_broker:
    # Local dev OR production without Redis: run tasks synchronously.
    # No Celery worker needed — tasks execute in the request cycle.
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_TASK_EAGER_PROPAGATES = True
else:
    CELERY_BROKER_URL = _celery_broker
    CELERY_RESULT_BACKEND = _celery_backend

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "Asia/Kolkata"


# ─────────────────────────────────────────────
# FRONTEND URL
# ─────────────────────────────────────────────
# Set FRONTEND_URL in Railway environment variables to your
# Railway-assigned domain, e.g. https://shopverse.up.railway.app
# ─────────────────────────────────────────────

FRONTEND_URL = os.getenv(
    "FRONTEND_URL",
    "http://127.0.0.1:8000",
).rstrip("/")


# ─────────────────────────────────────────────
# MESSAGE STORAGE
# ─────────────────────────────────────────────

MESSAGE_STORAGE = "django.contrib.messages.storage.session.SessionStorage"


# ─────────────────────────────────────────────
# LOGGING
# ─────────────────────────────────────────────

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
    },

    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },

    "root": {
        "handlers": ["console"],
        "level": "WARNING" if not DEBUG else "INFO",
    },

    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "WARNING" if not DEBUG else "INFO",
            "propagate": False,
        },
        "apps": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}